FROM golang:1.12.5-alpine3.9 as debug

# installing git
RUN apk update && apk upgrade && \
    apk add --no-cache git

RUN go get github.com/sirupsen/logrus
RUN go get github.com/buaazp/fasthttprouter
RUN go get github.com/valyala/fasthttp

WORKDIR /go/src/work
COPY ./src /go/src/work/

RUN go build -o app

######### START NEW IMAGE ###############

FROM alpine:3.9 as prod
COPY --from=dev /go/src/work/app /
CMD ./app