version: "3"
services: 
    csharp:
        container_name: csharp
        image: jwas91/csharp:1.0.0
        build: ./c#
    golang:
        container_name: golang
        image: jwas91/golang:1.0.0
        build: ./golang
    nodejs:
        container_name: nodejs
        image: jwas91/nodejs:1.0.0
        build: ./nodejs
    python:
        container_name: python
        image: jwas91/python:1.0.0
        build: ./python
