version: "3"
services: 
    csharp: 
        container_name: csharp # docker run -it -v ${PDW}:/work -w /work -p 5000:5000 jwas91/csharp:1.0.0 /bin/sh
        # docker exec -it csharp sh
        image: jwas91/csharp:1.0.0
        build: ./c#
        working_dir: /work
        entrypoint: /bin/sh
        stdin_open: true
        tty: true
        volumes: 
        -  ./c#/src/:/work
        ports: 
        -  5000:5000
    golang:
        container_name: golang
        image: jwas91/golang:1.0.0
        build: ./golang
        working_dir: /work
        entrypoint: /bin/sh
        stdin_open: true
        tty: true
        volumes: 
        -  ./golang/src/:/work
        ports: 
        -  5001:5000
    nodejs:
        container_name: nodejs
        image: jwas91/nodejs:1.0.0
        build: ./nodejs
        working_dir: /work
        entrypoint: /bin/sh
        stdin_open: true
        tty: true
        volumes: 
        -  ./nodejs/src/:/work
        ports: 
        -  5002:5000
    python:
        container_name: python
        image: jwas91/python:1.0.0
        build: ./python
        working_dir: /work
        entrypoint: /bin/sh
        stdin_open: true
        tty: true
        volumes: 
        -  ./python/src/:/work
        ports: 
        -  5003:5000
