version: "3"
services: 
    csharp: # docker run -it -v ${PWD}:/work -w /work -p 5000:5000 jwas91/csharp:1.0.0 /bin/sh
        container_name: csharp 
        # docker exec -it csharp sh
        # dotnet build
        # dotnet run
        image: jwas91/csharp:1.0.0
        build: 
            context: ./c#
            target: dev
        working_dir: /work      # command out for build.target.prod
        entrypoint: /bin/sh     # command out for build.target.prod
        stdin_open: true        # command out for build.target.prod
        tty: true               # command out for build.target.prod
        volumes: 
        -  ./c#/src/:/work
        ports: 
        -  5000:5000
    golang: # docker run -it -v ${PWD}:/work -w /work -p 5001:5000 jwas91/golang:1.0.0 /bin/sh
        container_name: golang
        # docker exec -it golang sh
        # go build
        # go ./work
        image: jwas91/golang:1.0.0
        build: 
            context: ./golang
            target: dev
        working_dir: /work      # command out for build.target.prod
        entrypoint: /bin/sh     # command out for build.target.prod
        stdin_open: true        # command out for build.target.prod
        tty: true               # command out for build.target.prod
        volumes: 
        -  ./golang/src/:/work
        ports: 
        -  5001:5000
    nodejs: # docker run -it -v ${PWD}:/work -w /work -p 5002:5000 jwas91/nodejs:1.0.0 /bin/sh
        container_name: nodejs
        # npm install
        # npm start
        image: jwas91/nodejs:1.0.0
        build: 
            context: ./nodejs
            target: dev
        working_dir: /work      # command out for build.target.prod
        entrypoint: /bin/sh     # command out for build.target.prod
        stdin_open: true        # command out for build.target.prod
        tty: true               # command out for build.target.prod
        volumes: 
        -  ./nodejs/src/:/work
        ports: 
        -  5002:5000
    python: # docker run -it -v ${PWD}:/work -w /work -p 5003:5000 jwas91/python:1.0.0 /bin/sh
        container_name: python
        # FLASK_APP=server.py flask run -h 0.0.0 -p 5000
        image: jwas91/python:1.0.0
        build: 
            context: ./python
            target: dev
        working_dir: /work      # command out for build.target.prod
        entrypoint: /bin/sh     # command out for build.target.prod
        stdin_open: true        # command out for build.target.prod
        tty: true               # command out for build.target.prod
        volumes: 
        -  ./python/src/:/work
        ports: 
        -  5003:5000
